# Generated by Django 4.2.13 on 2024-10-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='elective_group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
