# Generated by Django 4.2.13 on 2024-11-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="class_id",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_id",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="teacher",
            unique_together={("school", "teacher_id")},
        ),
    ]
