# Generated by Django 4.2.13 on 2024-11-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daytimetabledate",
            name="day_timetable",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_date",
                to="base.daytimetable",
            ),
        ),
    ]
