# Generated by Django 4.2.13 on 2024-07-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room_classroom_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='room_number',
        ),
        migrations.AddField(
            model_name='electivegroup',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electives_groups', to='base.standard'),
        ),
    ]
