# Generated by Django 4.2.13 on 2024-07-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_room_classroom_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="room_number",
        ),
    ]
