# Generated by Django 4.2.13 on 2024-11-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_classroom_class_id_alter_teacher_teacher_id_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="classroom",
            constraint=models.UniqueConstraint(
                fields=("school", "class_id"), name="unique_class_id_within_school"
            ),
        ),
    ]
