# Generated by Django 4.2.13 on 2024-08-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('school', 'room_number')},
        ),
    ]
