# Generated by Django 4.2.13 on 2024-09-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_number', 'school')},
        ),
    ]
