# Generated by Django 4.2.13 on 2024-12-10 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_useracademicschedule_academic_year_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacheractivitylog",
            name="day_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="base.daylesson",
            ),
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_number", models.PositiveIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "day_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="base.dayschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["period_number"],
                "unique_together": {("day_schedule", "period_number")},
            },
        ),
    ]
