# Generated by Django 4.2.13 on 2024-11-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_userconstraintsettings_avoid_elective_in_first_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconstraintsettings",
            name="avoid_first_half_period",
            field=models.BooleanField(default=False),
        ),
    ]
