# Generated by Django 4.2.13 on 2024-11-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_userconstraintsettings_avoid_first_half_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsubject",
            name="prevent_first_half_period",
            field=models.BooleanField(default=False),
        ),
    ]
