# Generated by Django 4.2.13 on 2024-09-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_timetable_hard_score_timetable_soft_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='multi_block_lessons',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
