# Generated by Django 4.2.13 on 2024-12-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_useracademicschedule_is_auto_timetable_creation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("INFO", "Information"),
                    ("ALERT", "Alert"),
                    ("REMINDER", "Reminder"),
                    ("DAYTIMETABLE_CREATION_ERROR", "Day Timetable Creation Error"),
                    ("CREATE_DAYTIMETABLE", "Create Day Timetable"),
                    ("UPDATE_DAYTIMETABLE", "Update Day Timetable"),
                    ("CHANGE_AND_CREATE", "Change and Create"),
                ],
                default="INFO",
                max_length=30,
            ),
        ),
    ]
