# Generated by Django 4.2.13 on 2024-08-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='electivegroup',
            name='preferred_rooms',
            field=models.ManyToManyField(related_name='electvie_grops', to='base.room'),
        ),
    ]
