# Generated by Django 4.2.13 on 2024-08-10 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_electivegroup_preferred_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
                ('occupied', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classroom_id', models.UUIDField()),
                ('division', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('optimal', models.BooleanField(default=False)),
                ('feasible', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='base.timetable')),
            ],
            options={
                'unique_together': {('teacher_id', 'timetable')},
            },
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=10)),
                ('period', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='base.timetable')),
            ],
            options={
                'unique_together': {('day_of_week', 'period', 'timetable')},
            },
        ),
        migrations.CreateModel(
            name='StandardLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('standard_id', models.UUIDField()),
                ('name', models.CharField(max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_levels', to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_levels', to='base.timetable')),
            ],
            options={
                'unique_together': {('standard_id', 'timetable')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alotted_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotted_lessons', to='base.tutor')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classsection')),
                ('classroom_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classroomassignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='base.timetable')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='base.timetable'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.standardlevel'),
        ),
        migrations.AddField(
            model_name='classsection',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sections', to='base.timetable'),
        ),
        migrations.AddField(
            model_name='classroomassignment',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to='base.timetable'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject_id', 'timetable')},
        ),
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together={('classroom_id', 'timetable')},
        ),
        migrations.AlterUniqueTogether(
            name='classroomassignment',
            unique_together={('room_id', 'timetable')},
        ),
    ]
