# Generated by Django 4.2.13 on 2024-09-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userconstraintsettings_consecutive_multi_block_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconstraintsettings',
            name='consecutive_multi_block_lessons',
            field=models.BooleanField(default=False),
        ),
    ]
