# Generated by Django 4.2.13 on 2024-11-22 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_timetabledayschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="class_teacher",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classroom_teacher",
                to="base.teacher",
            ),
        ),
        migrations.AddField(
            model_name="userconstraintsettings",
            name="assign_class_teacher_at_first_period",
            field=models.BooleanField(default=False),
        ),
    ]
