# Generated by Django 4.2.13 on 2024-11-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_classroom_class_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconstraintsettings",
            name="same_teacher_first_period_constraint",
            field=models.BooleanField(default=False),
        ),
    ]
