# Generated by Django 4.2.13 on 2024-08-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_classroomassignment_classsection_course_timetable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='feasible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='optimal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
