# Generated by Django 4.2.13 on 2024-09-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_userconstraintsettings_consecutive_multi_block_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconstraintsettings',
            name='tutor_free_period_constraint',
            field=models.BooleanField(default=True),
        ),
    ]
